# Generated by Django 2.2.2 on 2019-06-20 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_paciente', models.CharField(max_length=12)),
                ('nombres', models.CharField(max_length=20)),
                ('apellido_pat', models.CharField(max_length=10)),
                ('apellido_mat', models.CharField(max_length=10)),
                ('fecha_nac', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('ocupacion', models.CharField(max_length=10)),
                ('estado_civil', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=12)),
                ('prevision', models.CharField(max_length=20)),
            ],
        ),
    ]
