# Generated by Django 2.2.2 on 2019-06-20 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0002_auto_20190620_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nac',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 20, 13, 10, 10, 407044)),
        ),
    ]
