# Generated by Django 2.2.2 on 2019-06-21 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0003_auto_20190620_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nac',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 20, 20, 35, 37, 66342)),
        ),
    ]
