# Generated by Django 2.2.2 on 2019-06-21 03:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0004_auto_20190620_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='examenes',
            fields=[
                ('codiexamen', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nac',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 20, 23, 58, 10, 397285)),
        ),
        migrations.CreateModel(
            name='agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime(2019, 6, 20, 23, 58, 10, 397285))),
                ('hora', models.TimeField()),
                ('codiexmaen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.examenes')),
                ('rut_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.paciente')),
            ],
        ),
    ]
