# Generated by Django 2.2.2 on 2019-06-21 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0007_auto_20190620_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2019, 6, 21, 0, 1, 20, 206027)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nac',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 21, 0, 1, 20, 206027)),
        ),
    ]
