# Generated by Django 2.2.2 on 2019-06-21 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0009_auto_20190621_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='codiexmaen',
            new_name='codiexamen',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2019, 6, 21, 0, 54, 20, 765242)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nac',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 21, 0, 54, 20, 764246)),
        ),
    ]
