# Generated by Django 2.2.2 on 2019-06-21 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0010_auto_20190621_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2019, 6, 21, 0, 55, 33, 429864)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nac',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 21, 0, 55, 33, 429864)),
        ),
    ]
