# Generated by Django 2.2.2 on 2019-06-26 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0013_auto_20190621_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2019, 6, 26, 14, 0, 48, 159713)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nac',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 26, 14, 0, 48, 158715)),
        ),
    ]
