# Generated by Django 2.2.2 on 2019-07-08 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0015_auto_20190708_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField()),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.producto')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombres', models.CharField(max_length=20)),
                ('apellido_pat', models.CharField(max_length=10)),
                ('apellido_mat', models.CharField(max_length=10)),
                ('fecha_nac', models.DateTimeField(default=django.utils.timezone.now)),
                ('ocupacion', models.CharField(max_length=10)),
                ('estado_civil', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='agenda',
        ),
        migrations.DeleteModel(
            name='examenes',
        ),
        migrations.DeleteModel(
            name='paciente',
        ),
        migrations.AddField(
            model_name='servicio',
            name='rut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.usuario'),
        ),
    ]
