# Generated by Django 2.2.2 on 2019-07-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0016_auto_20190708_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=3, default=10000, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='storage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
