# Generated by Django 2.2.2 on 2019-07-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0017_auto_20190708_0401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='storage',
            new_name='stock',
        ),
    ]
