# Generated by Django 2.2.2 on 2019-07-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0018_auto_20190708_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=10000, max_digits=10),
        ),
    ]
