# Generated by Django 2.2.2 on 2019-07-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0019_auto_20190708_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
